import { 
  TenantCompany, 
  EmployeeUser, 
  InventoryItem, 
  InventoryLedgerEntry, 
  CustomerProfile, 
  TransactionRecord, 
  SystemActivityLog, 
  VendingMachineUnit, 
  MarketplaceIntegration 
} from './types';

export const TENANT_COMPANIES: TenantCompany[] = [
  {
    id: 'comp-1',
    name: 'Apex Vault Collectibles HQ',
    code: 'APEX-HQ',
    branchLocations: ['Downtown Flagship', 'Akihabara Station Branch', 'Westside Mall Vending Hub'],
    defaultTaxRate: 8.5,
    defaultCostMultiplier: 1.45,
    currencySymbol: '$',
  },
  {
    id: 'comp-2',
    name: 'Dragon Shield TCG Syndicate',
    code: 'DRAGON-SYN',
    branchLocations: ['Kyoto Vault', 'Osaka Namba Store'],
    defaultTaxRate: 10.0,
    defaultCostMultiplier: 1.35,
    currencySymbol: '¥',
  }
];

export const CURRENT_USER: EmployeeUser = {
  id: 'emp-101',
  companyId: 'comp-1',
  name: 'Marcus Vance',
  role: 'Owner',
  email: 'marcus@apexvault.tcg',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  branchLocation: 'Downtown Flagship',
  terminalId: 'TERM-01-POS',
};

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'VX-000001',
    companyId: 'comp-1',
    name: 'Charizard VMAX (Secret Rare Shiny)',
    setName: 'Shining Fates',
    cardNumber: 'SV107/SV122',
    rarity: 'Secret Rare',
    gradingCompany: 'PSA',
    gradeValue: '10',
    category: 'Slabs',
    images: {
      primary: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=500&q=80',
      back: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 180.00,
    sellingPrice: 320.00,
    quantity: 3,
    supplierName: 'Kanto Collectors Guild',
    paymentMethod: 'Instant Cash',
    storageLocation: 'Downtown Flagship - Vault Safe A1',
    purchaseDate: '2026-06-15',
    notes: 'Pristine centering, verified hologram.',
    status: 'In Vault',
    isStarred: true,
    marketPrice: 315.50,
    priceTrend: '+4.2% this week'
  },
  {
    id: 'VX-000002',
    companyId: 'comp-1',
    name: 'Prismatic Evolution Booster Box (Sealed)',
    setName: 'Scarlet & Violet',
    cardNumber: 'SEAL-SV-09',
    rarity: 'Sealed Case',
    gradingCompany: 'Raw',
    category: 'Booster Boxes',
    images: {
      primary: 'https://images.unsplash.com/photo-1638803040283-7a5ffd48dad5?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 85.00,
    sellingPrice: 145.00,
    quantity: 24,
    supplierName: 'Official Nintendo Distro',
    paymentMethod: 'ACH Net-30',
    storageLocation: 'Downtown Flagship - Floor Rack B3',
    purchaseDate: '2026-06-20',
    notes: 'Factory sealed case with Nintendo wrap.',
    status: 'On Floor',
    isStarred: false,
    marketPrice: 149.00,
    priceTrend: '+12% post-release'
  },
  {
    id: 'VX-000003',
    companyId: 'comp-1',
    name: 'Umbreon VMAX (Alternate Art)',
    setName: 'Evolving Skies',
    cardNumber: '215/203',
    rarity: 'Secret Rare',
    gradingCompany: 'BGS',
    gradeValue: '9.5 Black Label',
    category: 'Slabs',
    images: {
      primary: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 550.00,
    sellingPrice: 980.00,
    quantity: 1,
    supplierName: 'Elena Rostova (Trade-in)',
    paymentMethod: 'Store Credit',
    storageLocation: 'Downtown Flagship - Vault Safe A2',
    purchaseDate: '2026-06-22',
    notes: 'Moonbreon black label. Extremely high liquidity.',
    status: 'In Vault',
    isStarred: true,
    marketPrice: 965.00,
    priceTrend: '+8.1% MTD'
  },
  {
    id: 'VX-000004',
    companyId: 'comp-1',
    name: 'Black Lotus (Beta Edition)',
    setName: 'MTG Beta 1993',
    cardNumber: 'ART-001',
    rarity: 'Ultra Rare',
    gradingCompany: 'PSA',
    gradeValue: '8.5',
    category: 'Slabs',
    images: {
      primary: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 14500.00,
    sellingPrice: 24000.00,
    quantity: 1,
    supplierName: 'Sotheby Private Auction',
    paymentMethod: 'Wire Transfer',
    storageLocation: 'Downtown Flagship - High Security Chamber',
    purchaseDate: '2026-05-10',
    notes: 'Holy grail artifact. Insured with Lloyd’s.',
    status: 'Reserved',
    isStarred: true,
    marketPrice: 23500.00,
    priceTrend: '+1.5% QTD'
  },
  {
    id: 'VX-000005',
    companyId: 'comp-1',
    name: 'Apex Matte Black Toploaders (Pack of 25)',
    setName: 'Apex Supplies',
    cardNumber: 'ACC-TL-25',
    rarity: 'Common',
    gradingCompany: 'Raw',
    category: 'Toploaders',
    images: {
      primary: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 2.20,
    sellingPrice: 6.99,
    quantity: 140,
    supplierName: 'Shenzhen Polymers Ltd',
    paymentMethod: 'ACH Net-30',
    storageLocation: 'Downtown Flagship - Counter Display',
    purchaseDate: '2026-06-01',
    notes: 'High margin impulse buy accessory.',
    status: 'On Floor',
    isStarred: false,
    marketPrice: 6.50,
    priceTrend: 'Stable'
  },
  {
    id: 'VX-000006',
    companyId: 'comp-1',
    name: 'Japanese 151 Elite Trainer Box',
    setName: 'Scarlet & Violet 151',
    cardNumber: 'JP-151-ETB',
    rarity: 'Limited Edition',
    gradingCompany: 'Raw',
    category: 'ETBs',
    images: {
      primary: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 52.00,
    sellingPrice: 110.00,
    quantity: 18,
    supplierName: 'Tokyo Direct Import',
    paymentMethod: 'Credit Card',
    storageLocation: 'Akihabara Station Branch - Display Shelf 2',
    purchaseDate: '2026-06-18',
    notes: 'High demand from international tourists.',
    status: 'On Floor',
    isStarred: true,
    marketPrice: 115.00,
    priceTrend: '+18% YoY'
  },
  {
    id: 'VX-000007',
    companyId: 'comp-1',
    name: 'Pikachu Illustrator Promo (Replica Display)',
    setName: 'CoroCoro Comics',
    cardNumber: 'PROMO-98',
    rarity: 'Promo',
    gradingCompany: 'CGC',
    gradeValue: '9.0',
    category: 'Raw Cards',
    images: {
      primary: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 45.00,
    sellingPrice: 89.99,
    quantity: 8,
    supplierName: 'Local Trade-In Hub',
    paymentMethod: 'Cash',
    storageLocation: 'Westside Mall Vending Hub - Unit #4',
    purchaseDate: '2026-06-25',
    notes: 'Loaded into smart vending unit #4.',
    status: 'Vending Machine',
    isStarred: false,
    marketPrice: 92.00,
    priceTrend: 'Stable'
  },
  {
    id: 'VX-000008',
    companyId: 'comp-1',
    name: 'Apex Energy Elixir (Blueberry Citrus)',
    setName: 'Beverages',
    cardNumber: 'BEV-01',
    rarity: 'Consumable',
    category: 'Beverages',
    images: {
      primary: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80',
    },
    purchaseCost: 1.10,
    sellingPrice: 3.50,
    quantity: 85,
    supplierName: 'Metro Beverage Distro',
    storageLocation: 'Downtown Flagship - Beverage Cooler',
    purchaseDate: '2026-06-20',
    status: 'On Floor',
    marketPrice: 3.50,
    priceTrend: 'High Volume'
  }
];

export const INITIAL_LEDGERS: InventoryLedgerEntry[] = [
  {
    id: 'led-1',
    itemId: 'VX-000001',
    itemPermanentId: 'VX-000001',
    itemName: 'Charizard VMAX (Secret Rare Shiny)',
    companyId: 'comp-1',
    actorName: 'Marcus Vance',
    actorRole: 'Owner',
    actionType: 'ADD_ITEM',
    quantityDelta: +3,
    previousQuantity: 0,
    newQuantity: 3,
    costUnit: 180.00,
    priceUnit: 320.00,
    timestamp: '2026-06-15 10:14:22',
    notes: 'Intake from Kanto Collectors Guild lot.'
  },
  {
    id: 'led-2',
    itemId: 'VX-000003',
    itemPermanentId: 'VX-000003',
    itemName: 'Umbreon VMAX (Alternate Art)',
    companyId: 'comp-1',
    actorName: 'Sarah Jenkins',
    actorRole: 'Admin',
    actionType: 'TRADE_IN',
    quantityDelta: +1,
    previousQuantity: 0,
    newQuantity: 1,
    costUnit: 550.00,
    priceUnit: 980.00,
    timestamp: '2026-06-22 15:40:11',
    notes: 'Trade exchange with customer Elena Rostova.'
  },
  {
    id: 'led-3',
    itemId: 'VX-000002',
    itemPermanentId: 'VX-000002',
    itemName: 'Prismatic Evolution Booster Box',
    companyId: 'comp-1',
    actorName: 'Marcus Vance',
    actorRole: 'Owner',
    actionType: 'POS_SALE',
    quantityDelta: -2,
    previousQuantity: 26,
    newQuantity: 24,
    costUnit: 85.00,
    priceUnit: 145.00,
    timestamp: '2026-06-27 12:10:05',
    notes: 'POS Register checkout sale.'
  }
];

export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cust-1',
    companyId: 'comp-1',
    name: 'Alexander Pierce',
    email: 'apierce@venture.tcg',
    phone: '+1 (555) 382-9910',
    loyaltyPoints: 1450,
    storeCreditBalance: 125.00,
    lifetimeSpending: 4820.50,
    lifetimeTradesValue: 2100.00,
    memberSince: 'Jan 2025',
    tradesCount: 8,
    salesCount: 34,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    membershipTier: 'Apex VIP',
    notes: 'Prefers BGS 9.5+ vintage slabs. High ticket collector.'
  },
  {
    id: 'cust-2',
    companyId: 'comp-1',
    name: 'Elena Rostova',
    email: 'elena.r@anime.jp',
    phone: '+1 (555) 881-2244',
    loyaltyPoints: 890,
    storeCreditBalance: 450.00,
    lifetimeSpending: 2150.00,
    lifetimeTradesValue: 1850.00,
    memberSince: 'Mar 2025',
    tradesCount: 12,
    salesCount: 19,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    membershipTier: 'Gold',
    notes: 'Active trader. Loves Eeveelutions and Japanese alt promos.'
  },
  {
    id: 'cust-3',
    companyId: 'comp-1',
    name: 'David Chen',
    email: 'dchen@techlabs.co',
    phone: '+1 (555) 443-1199',
    loyaltyPoints: 310,
    storeCreditBalance: 15.00,
    lifetimeSpending: 640.00,
    lifetimeTradesValue: 120.00,
    memberSince: 'May 2026',
    tradesCount: 2,
    salesCount: 7,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    membershipTier: 'Silver',
    notes: 'Casual weekend tournament player. Buys sleeves and ETBs.'
  }
];

export const INITIAL_TRANSACTIONS: TransactionRecord[] = [
  {
    id: 'TX-9841',
    companyId: 'comp-1',
    timestamp: '10 mins ago',
    customerName: 'Alexander Pierce',
    customerId: 'cust-1',
    employeeName: 'Marcus Vance',
    itemsCount: 2,
    subtotal: 290.00,
    taxAmount: 24.65,
    discountAmount: 15.00,
    totalAmount: 299.65,
    tenderType: 'POS Sale',
    paymentMethods: ['Apple Pay ($299.65)'],
    notes: 'Redeemed VIP discount coupon.'
  },
  {
    id: 'TX-9840',
    companyId: 'comp-1',
    timestamp: '2 hours ago',
    customerName: 'Elena Rostova',
    customerId: 'cust-2',
    employeeName: 'Sarah Jenkins',
    itemsCount: 1,
    subtotal: 550.00,
    taxAmount: 0,
    discountAmount: 0,
    totalAmount: 550.00,
    tenderType: 'Trade Exchange',
    paymentMethods: ['Store Credit Issued ($550.00)'],
    notes: 'Traded in Umbreon VMAX Alt Art.'
  },
  {
    id: 'TX-9839',
    companyId: 'comp-1',
    timestamp: 'Yesterday',
    customerName: 'Smart Kiosk Walk-in',
    employeeName: 'Vending Fleet Bot',
    itemsCount: 1,
    subtotal: 89.99,
    taxAmount: 7.65,
    discountAmount: 0,
    totalAmount: 97.64,
    tenderType: 'Vending Purchase',
    paymentMethods: ['QR Stripe Instant'],
    notes: 'Dispensed from Westside Mall Unit #4.'
  }
];

export const INITIAL_ACTIVITY_LOGS: SystemActivityLog[] = [
  {
    id: 'act-1',
    companyId: 'comp-1',
    timestamp: '2026-06-27 19:40:12',
    actorName: 'Marcus Vance (Owner)',
    actionType: 'LOGIN',
    description: 'Authenticated via Google Workspace SSO into APEX-HQ terminal.',
    severity: 'success',
    ipAddress: '192.168.1.104',
    targetResource: 'Auth Gateway'
  },
  {
    id: 'act-2',
    companyId: 'comp-1',
    timestamp: '2026-06-27 19:15:00',
    actorName: 'TCGPlayer Cloud Cron',
    actionType: 'INTEGRATION_SYNC',
    description: 'Synchronized 1,420 market price trends across inventory items.',
    severity: 'info',
    ipAddress: '54.210.99.12',
    targetResource: 'Catalog Engine'
  },
  {
    id: 'act-3',
    companyId: 'comp-1',
    timestamp: '2026-06-27 18:30:44',
    actorName: 'Marcus Vance (Owner)',
    actionType: 'INVENTORY_CHANGE',
    description: 'Created permanent item VX-000008 (Apex Energy Elixir) with stock 85.',
    severity: 'info',
    ipAddress: '192.168.1.104',
    targetResource: 'VX-000008'
  },
  {
    id: 'act-4',
    companyId: 'comp-1',
    timestamp: '2026-06-27 16:10:22',
    actorName: 'Vending Unit #4 (Westside)',
    actionType: 'VENDING_PING',
    description: 'Telemetry healthy. Temperature: 18.5°C. Filled slots: 38/40.',
    severity: 'success',
    ipAddress: '10.0.4.88',
    targetResource: 'Fleet Command'
  }
];

export const INITIAL_VENDING_UNITS: VendingMachineUnit[] = [
  {
    id: 'VEND-01',
    companyId: 'comp-1',
    name: 'Apex Smart Hub Alpha',
    locationName: 'Westside Mall Main Concourse',
    status: 'Online',
    temperatureC: 18.4,
    signalStrength: '5G Ultra (98%)',
    lastPing: '34 secs ago',
    slotsCount: 40,
    filledSlots: 38,
    totalRevenueMonthly: 4120.50,
    qrActive: true
  },
  {
    id: 'VEND-02',
    companyId: 'comp-1',
    name: 'Akihabara Station Express',
    locationName: 'JR Line Exit 4 East Bay',
    status: 'Restock Needed',
    temperatureC: 19.1,
    signalStrength: 'Fiber Link (100%)',
    lastPing: '1 min ago',
    slotsCount: 60,
    filledSlots: 12,
    totalRevenueMonthly: 8940.00,
    qrActive: true
  },
  {
    id: 'VEND-03',
    companyId: 'comp-1',
    name: 'University Campus Kiosk',
    locationName: 'Student Union Lounge Bldg C',
    status: 'Online',
    temperatureC: 18.8,
    signalStrength: 'WiFi-6 (84%)',
    lastPing: '5 mins ago',
    slotsCount: 30,
    filledSlots: 27,
    totalRevenueMonthly: 1890.75,
    qrActive: true
  }
];

export const INITIAL_INTEGRATIONS: MarketplaceIntegration[] = [
  {
    id: 'mkt-tcgplayer',
    platformName: 'TCGPlayer',
    status: 'Connected',
    lastSynced: '12 mins ago',
    itemsCountSynced: 184,
    autoPriceSync: true,
    logoIcon: '🟢'
  },
  {
    id: 'mkt-ebay',
    platformName: 'eBay',
    status: 'Connected',
    lastSynced: '45 mins ago',
    itemsCountSynced: 42,
    autoPriceSync: true,
    logoIcon: '🟡'
  },
  {
    id: 'mkt-shopify',
    platformName: 'Shopify',
    status: 'Idle Sync',
    lastSynced: '2 hours ago',
    itemsCountSynced: 210,
    autoPriceSync: false,
    logoIcon: '🛍️'
  },
  {
    id: 'mkt-collectr',
    platformName: 'Collectr',
    status: 'Connected',
    lastSynced: 'Just now',
    itemsCountSynced: 120,
    autoPriceSync: true,
    logoIcon: '📊'
  },
  {
    id: 'mkt-psa',
    platformName: 'PSA',
    status: 'Requires Auth',
    lastSynced: '3 days ago',
    itemsCountSynced: 14,
    autoPriceSync: false,
    logoIcon: '🔴'
  },
  {
    id: 'mkt-pricecharting',
    platformName: 'PriceCharting',
    status: 'Connected',
    lastSynced: '1 hour ago',
    itemsCountSynced: 95,
    autoPriceSync: true,
    logoIcon: '📈'
  }
];
